service: jugda-sendinvites

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  memorySize: 128
  timeout: 10
  stage: prod
  deploymentBucket: dasniko.serverless.deployments.${self:provider.region}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ses:SendEmail
      Resource: "${file(sls-props.yml):mail.identity}"
    - Effect: Allow
      Action:
        - sns:Publish
      Resource: "${file(sls-props.yml):dlq}"
    - Effect: Allow
      Action:
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
      Resource: "*"
  environment:
    EVENTS_URL: ${file(sls-props.yml):events_url}
    MAIL_TO: ${file(sls-props.yml):mail.to}
    MAIL_FROM: ${file(sls-props.yml):mail.from}
    TWITTER_CONSUMER_KEY: ${file(sls-props.yml):twitter.consumer_key}
    TWITTER_CONSUMER_SECRET: ${file(sls-props.yml):twitter.consumer_secret}
    TWITTER_ACCESS_TOKEN_KEY: ${file(sls-props.yml):twitter.access_token_key}
    TWITTER_ACCESS_TOKEN_SECRET: ${file(sls-props.yml):twitter.access_token_secret}

package:
  exclude:
   - node_modules/aws-sdk/**
   - sls-props.yml
   - yarn.lock
   - autoinvites.iml
   - .idea/**

functions:
  cron:
    handler: index.handler
    events:
      # Invoke Lambda function every day at 9am (UTC)
      - schedule: cron(0 9 * * ? *)
    onError: "${file(sls-props.yml):dlq}"
