service: jugda-sendinvites

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-central-1
  memorySize: 128
  timeout: 10
  stage: prod
  deploymentBucket:
    name: dasniko.serverless.deployments.${self:provider.region}
  tracing:
    lambda: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ses:SendEmail
          Resource: "arn:aws:ses:${self:provider.region}:*:identity/jug-da.de"
  environment:
    EVENTS_URL: ${self:custom.autoinvites.eventsUrl}
    MAIL_TO: ${self:custom.autoinvites.mail.to}
    MAIL_FROM: ${self:custom.autoinvites.mail.from}
    MASTO_URL: ${self:custom.autoinvites.masto.url}
    MASTO_TOKEN: ${self:custom.autoinvites.masto.token}

custom: ${ssm:/aws/reference/secretsmanager/jugda-secrets}

package:
  patterns:
    - '!yarn.lock'
    - '!autoinvites.iml'
    - '!.idea/**'

functions:
  cron:
    handler: index.handler
    events:
      # Invoke Lambda function every weekday at 9am (UTC)
      - schedule: cron(0 9 ? * MON-FRI *)
    onError: ${self:custom.autoinvites.dlq}
