service: jugda-sendinvites

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-central-1
  memorySize: 128
  timeout: 10
  stage: prod
  deploymentBucket: dasniko.serverless.deployments.${self:provider.region}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sns:Publish
      Resource: "${file(sls-props.yml):dlq}"
    - Effect: Allow
      Action:
        - xray:PutTraceSegments
        - xray:PutTelemetryRecords
      Resource: "*"
  environment:
    EVENTS_URL: ${file(sls-props.yml):events_url}
    SMTP_HOST: ${file(sls-props.yml):smtp.host}
    SMTP_PASSWORD: ${file(sls-props.yml):smtp.password}
    SMTP_USER: ${file(sls-props.yml):smtp.user}
    TWITTER_CONSUMER_KEY: ${file(sls-props.yml):twitter.consumer_key}
    TWITTER_CONSUMER_SECRET: ${file(sls-props.yml):twitter.consumer_secret}
    TWITTER_ACCESS_TOKEN_KEY: ${file(sls-props.yml):twitter.access_token_key}
    TWITTER_ACCESS_TOKEN_SECRET: ${file(sls-props.yml):twitter.access_token_secret}

package:
  exclude:
   - sls-props.yml
   - yarn.lock
   - autoinvites.iml
   - .idea/**

functions:
  cron:
    handler: index.handler
    events:
      # Invoke Lambda function every day at 10am (GMT)
      - schedule: cron(0 10 * * ? *)
    onError: "${file(sls-props.yml):dlq}"
