service: send-invites

provider:
  name: aws
  runtime: nodejs4.3
  region: eu-west-1
  memorySize: 128
  timeout: 5
  stage: jugda
  deploymentBucket: dasniko.serverless.${self:provider.region}.deployments

functions:
  cron:
    handler: index.handler
    events:
      # Invoke Lambda function every day at 10am (GMT)
      - schedule: cron(0 10 * * ? *)
