service: jugda-sendinvites

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-central-1
  memorySize: 128
  timeout: 10
  stage: prod

functions:
  cron:
    handler: index.handler
    events:
      # Invoke Lambda function every day at 10am (GMT)
      - schedule: cron(0 10 * * ? *)
